name: PipelineSolution2

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: windows-latest

    steps:
      - name: Install Microsoft 365 CLI
        run: npm install -g @pnp/cli-microsoft365

      - name: Try login
        shell: pwsh
        run: |
          echo "🔐 Testing M365 login..."
          m365 login --authType certificate `
            --appId "7a4c0ac6-0f6a-4111-b80d-4ae60dc4ff5c" `
            --tenant "smalsusinfolabs.onmicrosoft.com" `
            --certificateBase64Encoded "${{ secrets.M365_CERT_BASE64 }}" `
            --password "${{ secrets.M365_CERT_PASSWORD }}"

          echo "🔍 Checking SharePoint connectivity..."
          m365 spo site get --url "https://smalsusinfolabs.sharepoint.com/sites/apps"
